//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaChStorage.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaChStorageEntities : DbContext
    {
        public MaChStorageEntities()
            : base("name=MaChStorageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<StorageMain> StorageMains { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<OrderPart> OrderParts { get; set; }
        public virtual DbSet<OrderPartsVW> OrderPartsVWs { get; set; }
        public virtual DbSet<OrdersVW> OrdersVWs { get; set; }
        public virtual DbSet<StorageVW> StorageVWs { get; set; }
        public virtual DbSet<ItemsVW> ItemsVWs { get; set; }
    }
}
