//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaChStorage.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersVW
    {
        public int Id { get; set; }
        public string Descrition { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public string Canceled { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Country { get; set; }
        public string Town { get; set; }
        public string Street { get; set; }
        public string Email { get; set; }
        public string WebPage { get; set; }
        public string Phone { get; set; }
    }
}
