//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaChStorage.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageVW
    {
        public int StorageId { get; set; }
        public int ItemId { get; set; }
        public double Quantity { get; set; }
        public string Placement { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> Reservation { get; set; }
    }
}
